sonar.projectKey=Matisk123_Project-IA
sonar.organization=matisk123
sonar.sources=app,routes,resources/js
sonar.tests=tests
sonar.php.tests.reportPath=reports/phpunit.xml
sonar.php.coverage.reportPaths=reports/clover.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,database/migrations/**
